version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leetcode-in-python
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: bash
    environment:
      - PYTHONUNBUFFERED=1
